### ISSUE TITLE
你好，请问friends_embeddings.pt是如何训练的，哪里能下载到

### ISSUE THREAD

**Issue by JoeshpCheung** [wxjiao/HiGRUs#13]
因为如果我将embeddings设置为None后，效果很差，比起论文差了将近30个点，也没改过源码

**Comment by PPC772** [comment]
> 因为如果我将embeddings设置为None后，效果很差，比起论文差了将近30个点，也没改过源码

我训练这个文件的时候报错了
Traceback (most recent call last):
  File "EmoMain.py", line 135, in <module>
    main()
  File "EmoMain.py", line 84, in main
    np_embedding = Utils.load_pretrain(args.d_word_vec, worddict, type='word2vec')
  File "C:\Users\ASUS\Desktop\HiGRUs-master\Utils.py", line 140, in load_pretrain
    word2vec = load_bin_vec(filename, diadict.word2index)
  File "C:\Users\ASUS\Desktop\HiGRUs-master\Utils.py", line 83, in load_bin_vec
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'word2vec300.bin'
请问你们是怎么解决的？谢谢！

**Comment by wxjiao** [comment]
@JoeshpCheung @PPC772 Hi，friends_embeddings.pt是根据词表从word2vec或者glove提供的预训练embedding中初始化的，链接分别如下：
wordvec: https://code.google.com/archive/p/word2vec/
glove: https://nlp.stanford.edu/projects/glove/

稍后我在readme中更新一下。
