### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by liuyijiang1994** [wxjiao/HiGRUs#9]
Hi Wenxiang,
  I have a little question about your paper.
  What the "(2.0)" means in "69.0(2.0)", is it means that the WA is in the range of [69-2, 69+2] ? If so, what causes that range?
  Tanks for your help!

**Comment by suncong132** [comment]
I have always suffered from a value error:

Traceback (most recent call last):
  File "EmoMain.py", line 132, in <module>
    main()
  File "EmoMain.py", line 108, in main
    focus_emo=focus_emo)
  File "/home/suncong/DUTIR/Learning/HiGRUs/EmoTrain.py", line 67, in emotrain
    log_prob = model(feat, lens)
  File "/home/suncong/anaconda3/envs/Learning/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/suncong/DUTIR/Learning/HiGRUs/Modules.py", line 166, in forward
    s_embed = self.uttenc(w_embed, lens, sa_mask)
  File "/home/suncong/anaconda3/envs/Learning/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/suncong/DUTIR/Learning/HiGRUs/Modules.py", line 100, in forward
    w_context = self.encoder(sents, lengths)
  File "/home/suncong/anaconda3/envs/Learning/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/suncong/DUTIR/Learning/HiGRUs/Modules.py", line 64, in forward
    sent_packed = pack_padded_sequence(s_embs, s_lens)
  File "/home/suncong/anaconda3/envs/Learning/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 258, in pack_padded_sequence
    lengths = torch.as_tensor(lengths, dtype=torch.int64)
ValueError: some of the strides of a given numpy array are negative. This is currently not supported, but will be added in future releases.

How can I solve it?

**Comment by liuyijiang1994** [comment]
s_lens = s_lens.copy()  you should add this line before         
sent_packed = pack_padded_sequence(s_embs, s_lens)
@suncong132

**Comment by suncong132** [comment]
Thank you very much!

**Comment by suncong132** [comment]
Thank you very much!
@liuyijiang1994

**Comment by wxjiao** [comment]
> Hi Wenxiang,
> I have a little question about your paper.
> What the "(2.0)" means in "69.0(2.0)", is it means that the WA is in the range of [69-2, 69+2] ? If so, what causes that range?
> Tanks for your help!

Hi @liuyijiang1994 , you are right about the number in the parentheses. In our paper, we didn't fixe the seeds for initialization or data shuffling. Instead, we reported the expectation and variance of results from repeated experiments. Such randomness results in the range you mentioned, which also demonstrates the robustness of each model to different settings.

**Comment by wxjiao** [comment]
> I have always suffered from a value error:
> 
> Traceback (most recent call last):
> File "EmoMain.py", line 132, in
> main()
> File "EmoMain.py", line 108, in main
> focus_emo=focus_emo)
> File "/home/suncong/DUTIR/Learning/HiGRUs/EmoTrain.py", line 67, in emotrain
> log_prob = model(feat, lens)
> File "/home/suncong/anaconda3/envs/Learning/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/suncong/DUTIR/Learning/HiGRUs/Modules.py", line 166, in forward
> s_embed = self.uttenc(w_embed, lens, sa_mask)
> File "/home/suncong/anaconda3/envs/Learning/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/suncong/DUTIR/Learning/HiGRUs/Modules.py", line 100, in forward
> w_context = self.encoder(sents, lengths)
> File "/home/suncong/anaconda3/envs/Learning/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/suncong/DUTIR/Learning/HiGRUs/Modules.py", line 64, in forward
> sent_packed = pack_padded_sequence(s_embs, s_lens)
> File "/home/suncong/anaconda3/envs/Learning/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 258, in pack_padded_sequence
> lengths = torch.as_tensor(lengths, dtype=torch.int64)
> ValueError: some of the strides of a given numpy array are negative. This is currently not supported, but will be added in future releases.
> 
> How can I solve it?

Hi @suncong132, sorry for the late reply. The issue you encountered might come from the compatibility issue of Pytorch. The code should work well in Pytorch v0.4.0 and v0.4.1. I haven't tried the solution suggested by @liuyijiang1994 (thanks though) but will check it ASAP.

**Comment by wxjiao** [comment]
> s_lens = s_lens.copy() you should add this line before
> sent_packed = pack_padded_sequence(s_embs, s_lens)
> @suncong132

Worked well, thanks!
